title: EM
tagline: play, create, move
email: email@example.com
description: >-
  play, create, move, embrace, love
url: "https://armsp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: me
twitter:
  username: me
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
# Build settings
markdown: kramdown
remote_theme: ItsPatrq/minimal-music-project
permalink: /:title.html
pagination:
  enabled: true
  per_page: 4
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
